zuul:
  routes:
    postulante:
      sensitive-headers:
      path: /postulante/**
      service-id: servicio-alumnos
    inscripcion:
      path: /inscripcion/**
      sensitive-headers:
      service-id: servicio-matricula
    uaa:
      path: /uaa/**
      sensitive-headers:
      service-id: micro-uaa 
eureka:  client:    register-with-eureka: false
    service-url:      default-zone: http://localhost:8761/eureka/
server:  port: 6565
  
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:7777/user
 
#Basic configuration SLF4j for development
#logging:
  #level:
   # org.springframework: ERROR
  #  com.mkyong: DEBUG
 # pattern:
  #  console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  #  file: "%d %p %c{1.} [%t] %m%n"
 # file: app.log
  
#Configuration SLF4j for production (logback-spring.xml)
spring:  profiles:    active:    - prod