spring:
  cloud:
    config:
      server:
        git:
          cloneOnStart: true
          uri: https://github.com/lilianabarrosc/Config-Microservicios-Eureka
          repos:
            servicio:
              pattern:
                - 'servicio-*'
              cloneOnStart: true
              uri: https://github.com/lilianabarrosc/Config-Microservicios
             
#HTTP Server
server:
  port: 4444