# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/universidad?useSSL=false
    username: root
    password: liliana10
  jpa:
    generate-ddl: true
    
